name: flutter_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # --- Thư viện ứng dụng ---
  provider: ^6.0.0       # Quản lý trạng thái
  localstore: ^1.3.0     # Database NoSQL
  intl: ^0.18.0          # Định dạng tiền tệ/ngày tháng
  uuid: ^4.0.0           # Tạo ID
  google_fonts: ^6.1.0   # Font chữ đẹp

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  # --- Công cụ hỗ trợ phát triển ---
  flutter_lints: ^4.0.0  # Kiểm tra lỗi code (dùng bản mới 4.0)
  mockito: ^5.4.0        # Mock data khi test
  build_runner: ^2.4.6   # Chạy lệnh build

flutter:
  uses-material-design: true